#!/usr/bin/env python3
from setup_utils import *
import os

# ids.storage_test

actions, arg, props = getActions("setup.properties", [])

if arg in ["CONFIGURE", "INSTALL"]:
    actions.checkNoErrors()

if arg == "INSTALL":
    try:
        app = actions.getAppName("ids.server")
        if app: actions.disableApp(app)
        actions.removeFromApplibs("ids.storage_test*.jar")
        actions.installToApplibs("ids.storage_test*.jar")
        actions.stopDomain()
        actions.startDomain()
        if app: actions.enableApp(app)
    except Exception as e:
        raise
        abort(str(e))

if arg == "UNINSTALL":
    try:
        actions.removeFromApplibs("ids.storage_test*.jar")
    except Exception as e:
        abort(str(e))
